### PR TITLE
feat(neon): build images for `Neon` (3000)

### PR DESCRIPTION
**Pull request by myii**
* Use `stable latest` & `git 3000` for `Neon` until bootstrap is fixed
  - https://github.com/saltstack/salt-bootstrap/issues/1429#issuecomment-585308951

### CODE REVIEW

**Comment by myii** [comment]
@javierbertoli One other thing, I'd like your opinion on a slight reordering:

* https://github.com/myii/salt-image-builder/commit/61670bea82e0331d158d13ef92b31618f4e18a02

The idea is to match the order used by the bootstrap.  It saves using the wrong ordering by mistake (something that happened to me while preparing this PR!).

I'm relaxed about ignoring this proposal so I'll only include it if you see the benefit of using it.  It can always be done in another PR anyway.

**Comment by javierbertoli** [comment]
> @javierbertoli One other thing, I'd like your opinion on a slight reordering:
> 
>     * [myii@61670be](https://github.com/myii/salt-image-builder/commit/61670bea82e0331d158d13ef92b31618f4e18a02)
> 
> The idea is to match the order used by the bootstrap. It saves using the wrong ordering by mistake (something that happened to me while preparing this PR!).

I'm OK if you want to submit this change into this PR too. I see no harm with it :smile:

**Comment by myii** [comment]
Rebased in preparation for `3000`, which has had its symlinks fixed in the upstream repos.  The four remaining failures are awaiting the bootstrap update.  I've just tested against a PR that has been provided to fix the bootstrap and these are all working now.

* https://github.com/saltstack/salt-bootstrap/pull/1433
* https://travis-ci.org/myii/salt-image-builder/builds/653108283

Once the bootstrap is updated, just have to restart the four instances in Travis to get this PR ready to be merged.

**Comment by myii** [comment]
The `bootstrap` PR has been merged and I've already re-run the remaining four jobs -- all passing now and this is ready to be considered for merging.

**Comment by javierbertoli** [comment]
Merged, then! Thanks for your great work, @myii

**Pull request merged**
